language: csharp
dotnet: 2.1.500
mono: none

before_install:
  - sudo apt-get install -y tree

script:
  - dotnet tool install --global GitVersion.Tool --version 4.0.1-beta1-50
  - export PATH="${PATH}:$HOME/.dotnet/tools"
  - dotnet gitversion /ensureassemblyinfo /updateassemblyinfo "AssemblyInfo_FromGitVersion.cs"
  - find ./ -name "*.csproj" | xargs dirname | xargs -L 1 cp "AssemblyInfo_FromGitVersion.cs"
  - noVersionsArgs='/p:GenerateAssemblyVersionAttribute=false /p:GenerateAssemblyFileVersionAttribute=false /p:GenerateAssemblyInformationalVersionAttribute=false'
  - find test/ -name "*.csproj" -exec dotnet test {} $noVersionsArgs \;
  - dotnet pack $noVersionsArgs
  - dotnet nuget push ./bin/Debug/*.nupkg -k $NugetApiKey -s nuget.org