language: csharp
dotnet: 2.1.500
mono: none
env:
  global:
    secure: nxTTZio8DE5m2YcrbwREmzn4ikg2FwJHAjKOAWPKUtgxfvPSAIpq6Qc5PNNErlu/rcWf1xaOaY4zuP3u4LXCzYC/5Z2KuyjQQhwlqkvL4A7HRq2+tRbE73Ota7UyBAtCCyug7tjW+sNmm3hORE4xZdb9MMcgZ4Q/vKRCbn+WTDSjJ7mV8zckoiz3wG+gya4AxyuTuj/Zk4p0QIH4MCVpAOIkxhhRngUCGz5pseM06bFwIt6U1a5L1izrSmqb3T6rp+qdQ9H2qxLG8LBqFYwrBCKG2s/DO+ZudCN/7r4qKtHsycw40/2Qt7WPNhQG763A9lDYRMNhi0juVztx1iUr0I+ncDkBi+XccPNK5P5NA4zdRGVl5S6HXRiOUwRtIgebXqDKc40qOesFuFODIYN4FmYsGOzoip2NfWJxWKnyVZ7nmAShh3d0V2HJ7G6uNZVxzffXqzxqXlh3BRmWndthX30rKTVEsAmGIhGXnkLTiYMpL0+TXcj1vlQ7lpO9NfpQnhiTVP0Y/4qPgw97TSZFPSf/ebaHEG1MivEGwbGhV0O81l7D/OKd9vsJY6lJfABZNPLvUTe8/KE3vD+oYjTkD267xPIyiuYhcuFA3kTYmSaYPzrx24Z+DeRZnWn/yIwRM3mMgUNjqWB7E3fA0XKmfk2rtb91KhwtF4roKHT5PVg=

script:
  - dotnet restore
  - dotnet pack
  - dotnet nuget push .\bin\Debug\test-nuget.1.0.0.nupkg -k $NugetApiKey -s nuget.org