language: csharp
dotnet: 2.1.500
mono: none

git:
  depth: false

install:
  - dotnet tool install --global GitVersion.Tool --version 4.0.1-beta1-50

before_script:
  - export PATH="${PATH}:$HOME/.dotnet/tools"
  - assemblyInfoFileName="AssemblyInfo_FromGitVersion.cs"
  - noVersionsArgs='/p:GenerateAssemblyVersionAttribute=false /p:GenerateAssemblyFileVersionAttribute=false /p:GenerateAssemblyInformationalVersionAttribute=false'

script:
  - dotnet gitversion /ensureassemblyinfo /updateassemblyinfo $assemblyInfoFileName
  - find ./ -name "*.csproj" | xargs dirname | xargs -L 1 cp $assemblyInfoFileName
  - find test/ -name "*.csproj" -exec dotnet test {} $noVersionsArgs \;
  - dotnet pack ./test-nuget/test-nuget.csproj $noVersionsArgs
  - dotnet nuget push ./test-nuget/bin/Debug/*.nupkg -k $NugetApiKey -s nuget.org